# This is an example of a Theme contained in a text file.
# Use a PropertyMetalTheme object to load it.

# This isn't really meant to be a great theme, but is just
# an example of how to create one from a text file.

# See MetalworksFrame.java for an example of how to load this.

name=Charcoal
primary1=133,66,66
primary2=166,99,99
primary3=199,99,99
secondary1=10,0,0
secondary2=151,51,51
secondary3=202,102,102
black=0,0,0
white=255,255,255
