/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package part8;

import java.rmi.*;
import javax.ejb.*;
import part8.SFTransactionRemote;

public interface SFTransactionHome extends EJBHome {
    public SFTransactionRemote create()
        throws RemoteException, CreateException;
}
