/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package part9.Client;

import java.rmi.*;
import javax.ejb.*;
import part9.Client.BeanClientRemote;

public interface BeanClientHome extends EJBHome {
    public BeanClientRemote create()
        throws RemoteException, CreateException;
}
