/* Show how to use the classes generated by scomp tool to get/create data from xml doc
Version : 1.0
Author : Team -J
*/

import org.openuri.easypo.*;
import java.io.File;

public class myprog{
public static void main(String a[])throws Exception{
	File xml_file = new File("input1.xml");
	PurchaseOrderDocument pod= PurchaseOrderDocument.Factory.parse(xml_file);
	System.out.println("successfully read(parse) your xml doc " +pod.getClass());
	PurchaseOrderDocument.PurchaseOrder po = pod.getPurchaseOrder();
	Customer c = po.getCustomer();
	System.out.println(c.getName());
	System.out.println(c.getAge());
	System.out.println(c.getAddress());
	Shipper s = po.getShipper();
	System.out.println(s.getName());
	System.out.println(s.getPerOunceRate());
	System.out.println("no of line items ="+po.sizeOfLineItemArray());
	LineItem li = po.getLineItemArray(0);
	System.out.println(li.getDescription());
	System.out.println(li.getPrice());
	System.out.println(li.getQuantity());


}
}