/* shows how to implement a tag handler.
Version: 1.0
Author : Team-J
*/

package inet;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import java.io.*;

/* TagSupport implements the Tag which has doStartTag and doEndTag methods. */

public class tagClass extends TagSupport
{
    String attrib1;
    
    public void setAttrib1(String a1) {
        attrib1 = a1;
    }

    public int doEndTag() throws JspException {
      JspWriter out = pageContext.getOut();
        try {
            out.println("<body> value of attrib1 used in jsp = "+ attrib1);
            out.println("</body></html>");
        } catch (IOException ex) {
            throw new JspTagException("IOException: "+ex.toString());
        }
        return super.doEndTag();
/* we can return EVAL_PAGE  to tell jsp engine has to continue evaluating the rest of the page
SKIP_PAGE if the rest of page has to be ignored.*/
    }
public int doStartTag() throws JspException {
	try {
		pageContext.getOut().print("<Html><head><title> Generated by tagClass</title></head>");
	 } catch (Exception ex) {
		 throw new JspTagException("SimpleTag: " + e.getMessage());
	 }
 	return SKIP_BODY; /* as there will be no body we are returning this value */
} 

}

    
        
    
