/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package sync;

import java.rmi.*;
import javax.ejb.*;
import sync.SSTransRemote;

public interface SSTransHome extends EJBHome {
    public SSTransRemote create()
        throws RemoteException, CreateException;
}
