<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example to show the details of the engine
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>

<HTML>
<HEAD>
<TITLE>JSP Engine info</TITLE>
</HEAD>

<BODY>
<H2>Jsp engine info</H2>
<%
// JspFactory is an abstract class that will be implemented by jsp engine
JspFactory  jspf = JspFactory.getDefaultFactory() ; // actual class depends on implementation
out.println(" <br> class implementing jspfactory is " + jspf);
out.println(" <br> <br>" );
JspEngineInfo  ei = jspf.getEngineInfo();
out.println(ei.getSpecificationVersion() );

//out.println("U'r current jsp engine supports ...." + ei.getSpecificationVersion());

%>

<br>
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>