<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on how to use java beans to write business logic
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ page errorPage="errpage.jsp"%>
<HTML>
<HEAD>
<TITLE>UseBean Example</TITLE>
</HEAD>

<BODY>
<H2>shows how to use java bean from jsp</H2>
<!-- In this example we will generate the form from this jsp file only
based on the value of submit parameter
-->
<% if( request.getParameter("submit")== null) {%>

<form method="get" action="login.jsp">
<P>
<INPUT TYPE="textbox" NAME="name">
<P>
<P>
<INPUT TYPE="password" NAME="pass">
<P>
<INPUT TYPE="SUBMIT" NAME="submit">
</FORM>
<%}
else {
%>

   <% 
	out.println(" Thanks for visiting us");
// we are supposed to check whether this visitor is a valid user or not
	out.println("<br> username = " +request.getParameter("name"));
	out.println("<br> password = " +request.getParameter("pass"));
      session.putValue("isloggedin", new Boolean(true));
    %>
<%
}// end of else
%>	
	<br>This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>