<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on jsp
Comment is written like this in jsp, in this example we will not
write even a single line of java code.
-->
<HTML>
<HEAD>
<TITLE>First Jsp Example</TITLE>
</HEAD>

<BODY>
<H2>Hello World</H2>
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!!
</BODY>
</HTML>