<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Application on how to use application object in a jsp page.
An application object can be used to store java objects (similar
to session object) which can be shared between multiple sessions.
Application object is servletcontext object in servlets. This can
be used to get and store the reference to objects that can be shared
between multiple sessions. 

(we can create database connections and store them in application
object, which can be shared between multiple sessions)
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ page errorPage="errpage.jsp"%>

<HTML>
<HEAD>
<TITLE>example on using application object</TITLE>
</HEAD>

<BODY>
<H2>example on using application object<H2>
<!-- we will set that the content expires immediately.
-->
<%
	out.println(" u'r html content that is dynamically generated goes here"); 
	application.setAttribute("somekey",new String("any java object can be stored"));
  %>
	<br>This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>
<a href="/App2.jsp">click here to open app2.jsp</a> 
<%@ include file="copyright.html" %> 

</BODY>
</HTML>