<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Application on how to use application object in a jsp page.
An application object can be used to store java objects (similar
to session object) which can be shared between multiple sessions.

-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ page errorPage="errpage.jsp"%>

<HTML>
<HEAD>
<TITLE>example on using application object</TITLE>
</HEAD>

<BODY>
<H2>example on using application object<H2>
<!-- we will set that the content expires immediately.
-->
<%
	out.println(" u'r html content that is dynamically generated goes here"); 
	String s = (String)application.getAttribute("somekey");
	out.println(" Here is an attribute that can be stored in application object .....  "+ s);
  %>
	<br>This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>
<%@ include file="copyright.html" %> 

</BODY>
</HTML>