<%@ page errorPage="errpage.jsp"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on how to forward request from one jsp to another jsp.

Note run this example using  page buffer="none" (never do this in real impl.

-->

<%@ page info=" This directive is used to give information about the page" %>


<HTML>
<HEAD>
<TITLE>Title of forward </TITLE>
</HEAD>

<BODY>
<H2>  This is html content from forward.jsp file<H2>
	Is this content visible to u when you run this jsp ???

	<br>This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>
// when some condition is met we may decide to forward this request to another jsp file
// from here
<jsp:forward page="/recv.jsp"> 
</jsp:forward> 

<%@ include file="copyright.html" %> 

</BODY>
</HTML>