<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on how to include init/destroy methods in jsp pages
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>

<HTML>
<HEAD>
<TITLE>writing init/destroy methods</TITLE>
</HEAD>

<BODY>
<H2>Methods in JSP PAGE</H2>
<%!
public void jspInit()	{
	System.out.println(" inside jsp init method");
}

public void jspDestroy() 	{
	System.out.println(" inside jsp destroy method");
}
%>

<br>
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>