/* Show how to use the classes generated by scomp tool to get/create data from xml doc
Version : 1.0
Author : Team -J
*/

import info.inetsolv.po.*;
import java.io.File;

public class ReadData{
public static void main(String a[])throws Exception{
	File xml_file = new File("input1.xml");
	PurchaseOrderDocument pod= PurchaseOrderDocument.Factory.parse(xml_file);
	PurchaseOrderDocument.PurchaseOrder po = pod.getPurchaseOrder();
	PurchaseOrderDocument.PurchaseOrder.Customer cus= po.getCustomer();
	PurchaseOrderDocument.PurchaseOrder.LineItem li = po.getLineItemArray(0);
	System.out.println(cus.getName());
	System.out.println(cus.getAge());
	System.out.println(cus.getAddress());
	System.out.println(cus.getSa());
	System.out.println("no of line items ="+po.sizeOfLineItemArray());
	System.out.println(li.getDescription());
	System.out.println(li.getPrice());
	System.out.println(li.getQuantity());
}
}