/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Nc */

#ifndef _Included_Nc
#define _Included_Nc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Nc
 * Method:    methodCalledbyNM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Nc_methodCalledbyNM
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
