/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package part5;

import java.rmi.*;
import javax.ejb.*;
import part5.SFSesRemote;

public interface SFSesHome extends EJBHome {
// may fail to create an object so we need to declare that this method
// throws CreateException
// we can have multiple create methods
    public SFSesRemote create()
        throws RemoteException, CreateException;
    public SFSesRemote create(String FName)
        throws RemoteException, CreateException;
// in some entity beans we need not declare the above also.
}
