insert into jspshop_class values('Object', 'this is the base object from which stuff is extended from');
insert into jspshop_class values('Container', 'for adding objects underneath');
insert into jspshop_class values('User', 'the main user class');
insert into jspshop_class values('Group', 'for grouping users together');
insert into jspshop_type values(1, 'Right');
insert into jspshop_property values(1,'Security','Object');
insert into jspshop_property values(2,'Membership','Group');
insert into jspshop_property values(3, 'Membership','User');
insert into jspshop_property values(4, 'Password', 'User');
insert into jspshop_property values(5, 'Verified', 'User');
insert into jspshop_propertytype values(1,1,1);
insert into jspshop_object values(1,'.-1',-1,'Root','Container');
insert into jspshop_object values(2,'.1.-1',1,'Administrator','User');
insert into jspshop_value values(1,1,1,'2');
insert into jspshop_typevalue values(1,1,'15',1);
insert into jspshop_value values(2,4,2,'21232f297a57a5a743894a0e4a801fc3');
insert into jspshop_value values(3,5,2,'true');
insert into com_evermind_ejb_counter values('com.submersion.jspshop.ejb.Object',11);
insert into com_evermind_ejb_counter values('com.submersion.jspshop.ejb.Value',11);
insert into com_evermind_ejb_counter values('com.submersion.jspshop.ejb.TypeValue',11);

create index jspshop_class_context on jspshop_class(context);
create index jspshop_class_parentname on jspshop_class(parentname);
create index jspshop_object_classname on jspshop_object(classname);
create index jspshop_object_context on jspshop_object(context);
create index jspshop_object_parentid on jspshop_object(parentid);
create index jspshop_property_classname on jspshop_property(classname);
create index jspshop_property_name on jspshop_property(name);
create index jspshop_propertytype_propertyid on jspshop_propertytype(propertyid);
create index jspshop_propertytype_typeid on jspshop_propertytype(typeid);
create index jspshop_typevalue_typeid on jspshop_typevalue(typeid);
create index jspshop_typevalue_value on jspshop_typevalue(Value);
create index jspshop_typevalue_valueid on jspshop_typevalue(valueid);
create index jspshop_type_name on jspshop_type(name);
create index jspshop_value_objectid on jspshop_value(objectid);
create index jspshop_value_propertyid on jspshop_value(propertyid);
create index jspshop_value_value on jspshop_value(value);
