/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package part6;

import java.rmi.*;
import javax.ejb.*;
import part6.TransRemote;

public interface TransHome extends EJBHome {
    public TransRemote create()throws RemoteException, CreateException;
}
