<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on jsp page directive
in this example we will show some of the page directives. Page directive can be kept
at any part of the file but it would be better to place it at the begining of the file.
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<!-- Check below on how to use include directive
--->
<HTML>
<HEAD>
<TITLE>First Jsp Example</TITLE>
</HEAD>

<BODY>
<H2>Hello World</H2>
	Date :: <%=new Date()%> 
<br><br> Date is generated by using an expression in jsp file <br><br>
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>