<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
This page can be accessed by only those who has logged in.

We have used checksigned.jsp to make sure that this visitor can access
this page.
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ include file="CheckSigned.jsp" %> 
<%@ page errorPage="errpage.jsp"%>
<HTML>
<HEAD>
<TITLE>Lot's of info</TITLE>
</HEAD>

<BODY>
<H2>U have logged in so u can view this page</H2>

U'r content goes here. <br><br><br>

	<br>This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>