/*  Sample showing how to develop EJB Home Interface , The class
 that implements this interface will be auomatically generated by
 EJB Server on which this EJB will be deployed.
 Version : 1.0
 Author : Team - J
*/

package cmt;

import java.rmi.*;
import javax.ejb.*;
import cmt.CMTransRemote;

public interface CMTransHome extends EJBHome {
    public CMTransRemote create()
        throws RemoteException, CreateException;
}
