package PJWS;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Oct 16 01:29:24 IST 2003
 */

public interface PJWSIF extends java.rmi.Remote{



  /**
   * method2 
   */

  public java.lang.String method2(java.lang.String string, java.lang.String string0) 
       throws java.rmi.RemoteException ;




  /**
   * method1 
   */

  public java.lang.String method1(java.lang.String string) 
       throws java.rmi.RemoteException ;




}

