<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example shows how to de velop an error page
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ page isErrorPage="true"%>
<%@ page import="java.io.*,java.util.*"%>
<HTML>
<HEAD>
<TITLE>Error Details</TITLE>
</HEAD>
	Help us in making this site Error Free. <br><br>
<BODY>

   <% 
	out.println( "we have used exception object here<br><br>");
	out.println(exception);
	out.println(" Please send the url u have accessed and the content of this to<br><br> bug-report@stud.inetsolv.com");
    %>	
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>