<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on how to include methods in jsp pages
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>

<HTML>
<HEAD>
<TITLE>writing methods</TITLE>
</HEAD>

<BODY>
<H2>Methods in JSP PAGE</H2>
<!-- we can include the declaration of vailables that can be used
in a page as shown below we can write methods that can be called
from this page in declarative section, this example is same as scriptlet
but shows another way of doing the same things using implicit variables 
(such as out)
-->
<%!
	int count =0;
	void printDate(HttpServletRequest request, HttpServletResponse response ){
		//out.print(" This output is generated from a method <br>");
// we cannot access out variable here as it is available for the service method
// check the code of servlet for this by uncommenting above line.
   JspFactory          na_jsp_factory = JspFactory.getDefaultFactory();
   PageContext         pageContext    = na_jsp_factory.getPageContext( this, request, response, "null", true, 8, true );
   JspWriter           out            = pageContext.getOut();
// we have pulled this code from the complied servlet. We always love to
// go deep to understand every thing
	}
%>


   <% for (count=0;count <10;count++) {
		printDate(request,response);
		out.println(" some html stuff goes here <br><br>");
		out.println(" some html stuff goes here <br><br>");

     }%>	
<br>
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>