<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- 
Example on how to use error pages
-->

<%@ page info=" This directive is used to give information about the page" %>
<%@ page language="java"%>
<%@ page errorPage="errpage.jsp"%>
<%@ page import="java.io.*,java.util.*"%>
<HTML>
<HEAD>
<TITLE>First Jsp Example</TITLE>
</HEAD>

<BODY>
<H2>shows how to use error pages</H2>
<!-- shows how error pages can be used
-->
   <% out.println("Date ::::"+new Date());
	try{
		FileInputStream is = new FileInputStream("sgfdg");
		out.print(is.read());
	 } catch(Exception e){ throw e;}
    %>	
	This file is generated by INteSolv Students. <br><br><br>
Thanks for visiting us !!!! <br><br>

<%@ include file="copyright.html" %> 

</BODY>
</HTML>